config/routes.rb
Rails.application.routes.draw do
	root 'aurthors#welcome'
	resources :aurthors
	resources :books
	get '/index', to: 'aurthors#index'
	get '/indexb', to: 'books#indexb'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aurthor.rb
class Aurthor < ApplicationRecord
	has_and_belongs_to_many :books
end

app/models/aurthors_book.rb
class AurthorsBook < ApplicationRecord
  belongs_to :Aurthor
  belongs_to :Book
end

app/models/book.rb
class Book < ApplicationRecord
	has_and_belongs_to_many :aurthor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/aurthors_controller.rb
class AurthorsController < ApplicationController
	def index
		@aurthors = Aurthor.all.order('created_at DESC')

	end
	def new
		@aurthor = Aurthor.new

	end
	def create
		@aurthor = Aurthor.new(aurthor_params)
		if @aurthor.save
		redirect_to @aurthor
	else
		render 'new'
	end
		
	end
	def show
		@aurthor = Aurthor.find(params[:id])
	end
	def edit
		@aurthor = Aurthor.find(params[:id])

	end
	def update
		@aurthor = Aurthor.find(params[:id])
		if @aurthor.update(aurthor_params)
			redirect_to @aurthor
		else
			render 'edit'
		end
	end
	def destroy
		@aurthor = Aurthor.find(params[:id])
		@aurthor.destroy
		redirect_to root_path

		
	end

	private

	def aurthor_params
		params.require(:aurthor).permit( :first_name, :last_name, :date_of_birth)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def indexb
		@books = Book.all.order('created_at DESC')

	end
	def new
		@book = Book.new
		

	end
	def create
		@book = Book.new(book_params)
		if @book.save
		redirect_to @book
	else
		render 'new'
	end
		
	end
	def show
		@book = Book.find(params[:id])
	end
	def edit
		@book = Book.find(params[:id])

	end
	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			redirect_to @book
		else
			render 'edit'
		end
	end
	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to root_path

		
	end

	private

	def book_params
		params.require(:book).permit( :book_title)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aurthor_helper.rb
module AurthorHelper
end

app/helpers/aurthors_helper.rb
module AurthorsHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/aurthors/_form.html.erb
<%= form_for @aurthor do |f| %>
<p>
	<%= f.label :first_name %><br>
	<%= f.text_field :first_name %>
</p>
<p>
	<%= f.label :last_name %><br>
	<%= f.text_field :last_name %>
</p>
<p>
	<%= f.label :date_of_birth %><br>
	<%= f.text_field :date_of_birth %>
</p>
<p>
	<%= f.submit %>
</p>

<% end %>

app/views/aurthors/edit.html.erb
<h1>Edit Aurthor</h1>
<%= render 'form' %>

app/views/aurthors/index.html.erb
<% @aurthors.each do |aurthor| %>
<h1><%= link_to aurthor.first_name, aurthor %></h1>
<% end %>

app/views/aurthors/new.html.erb
<h1>Add Aurthor</h1>
<%= render 'form' %>

app/views/aurthors/show.html.erb
First Name:  <%= @aurthor.first_name %><br>
Last Name:  <%= @aurthor.last_name %><br>
DOB: <%= @aurthor.date_of_birth %><br>
<%= link_to 'Edit', edit_aurthor_path(@aurthor) %> |
<%= link_to 'Delete', aurthor_path(@aurthor), method: :delete, data: {confirm: "are you sure"} %>

app/views/aurthors/welcome.html.erb
<button><h1><%= link_to "Add aurthor", new_aurthor_path %></h1></button><br><br>
<button><h1><%= link_to "Show aurthor list", index_path %></h1></button><br><br>

<button><h1><%= link_to "Add Book", new_book_path %></h1></button><br><br>
<button><h1><%= link_to "Show Book list", indexb_path %></h1></button>

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
<p>
	<%= f.label :book_title %><br>
	<%= f.text_field :book_title %>
</p>
<p>
	<%= f.submit %>
</p>

<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= render 'form' %>

app/views/books/indexb.html.erb
<% @books.each do |book| %>
<h1><%= link_to book.book_title, book %></h1>

<% end %>

app/views/books/new.html.erb
<h1>Add Book</h1>
<%= render 'form' %>

app/views/books/show.html.erb
First Name:  <%= @book.book_title %><br>
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Delete', book_path(@book), method: :delete, data: {confirm: "are you sure"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>